### PR TITLE
chore: update electron versions

### PR DESCRIPTION
**Pull request by setchy**
Update electron versions to include 30, 31

### CODE REVIEW

**Comment by amaury1093** [comment]
Could you fix the conflicts? I'll merge right after (if tests pass)

**Comment by setchy** [comment]
> Could you fix the conflicts? I'll merge right after (if tests pass)

conflicts resolved

**Comment by amaury1093** [comment]
Published in v9.5.0

**Comment by setchy** [comment]
@amaury1093 - should there be an updated CHANGELOG.md?

**Comment by amaury1093** [comment]
Done!

**Comment by gobengo** [comment]
could use something like this for electron v34 :/

**Comment by setchy** [comment]
> could use something like this for electron v34 :/

https://github.com/max-mapper/menubar/pull/486

**Pull request merged**
